const pets = [
  {
    petName: "Deloba",
    petId: 101,
    species: "dog",
    caretakerName: "Sam",
    age: 8,
    favoriteFood: "watermelon",
    caretakerAge: "27",
    weightInPounds: 15,
    friendsWith: ["Panda", "Chewy", "Akira"],
    dueForCheckup: false,
  },
  {
    petName: "Tuba",
    petId: 102,
    species: "spotted gecko",
    caretakerName: "Ari",
    age: 2,
    favoriteFood: "mealworms",
    caretakerAge: "26",
    weightInPounds: 0.1,
    friendsWith: ["Lizzie", "Panda"],
    dueForCheckup: true,
  },
  {
    petName: "Percy",
    petId: 103,
    species: "cat",
    caretakerName: "Nicole",
    age: 1,
    favoriteFood: "fish",
    caretakerAge: "29",
    weightInPounds: 12,
    friendsWith: ["Max", "Remy", "Chewy"],
    dueForCheckup: true,
  },
  {
    petName: "Monkey",
    petId: 104,
    species: "cat",
    caretakerName: "Katie",
    age: 10,
    favoriteFood: "dog food",
    caretakerAge: "17",
    weightInPounds: 14,
    friendsWith: ["Remy", "Max", "Gumby"],
    dueForCheckup: true,
  },
  {
    petName: "Gia",
    petId: 105,
    species: "dog",
    caretakerName: "Steven",
    age: 3,
    favoriteFood: "salami",
    caretakerAge: "34",
    weightInPounds: 25,
    friendsWith: ["Akira", "Mimi", "Max"],
    dueForCheckup: false,
  },
  {
    petName: "Gumby",
    petId: 106,
    species: "cat",
    caretakerName: "John",
    age: 6,
    favoriteFood: "bacon",
    caretakerAge: "61",
    weightInPounds: 18,
    friendsWith: [
      "Honey",
      "Monkey",
      "Luda",
      "Lizzie",
      "Mimi",
      "Akira",
      "Panda",
      "Remy",
    ],
    dueForCheckup: true,
  },
];

module.exports = pets;
